<?php
use Drupal\Core\Routing\RouteMatchInterface;

function parentingslider_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.parentingslider':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('This dispaly information what you enter your application.') . '</p>';
        return $output;

        default:
    }
}

function parentingslider_theme() {
    return [
        'parentingslider_description' => [
            'template' => 'description',
            'variables' => [],
        ],
    ];
}