<?php
use Drupal\Core\Routing\RouteMatchInterface;

function parenting_slider_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        case 'help.page.parenting_slider':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('This dispaly information what you enter your application.') . '</p>';
        return $output;

        default:
    }
}

function parenting_slider_theme() {
    return [
        'parenting_slider_description' => [
            'template' => 'description',
            'variables' => [],
        ],
    ];
}